### ISSUE TITLE
运行3.2的时候出了这个问题，萌新求问

### ISSUE THREAD

**Issue by wheelxxx** [liuxing/node-blog#2]
配置完 routes/home.js , index.js        /index.js 还有 views/index.html 代码和示例是一样的 也没有少做什么步骤 貌似， 服务启动是ok的 但是访问3000就会出现 Internal Server Error
看控制台显示如下
TypeError: ctx.render is not a function
      at index (/Users/kaixin1002/WebstormProjects/blog/routes/home.js:3:13)
      at dispatch (/Users/kaixin1002/WebstormProjects/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
      at next (/Users/kaixin1002/WebstormProjects/blog/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
      at /Users/kaixin1002/WebstormProjects/blog/node_modules/koa-router/lib/router.js:346:16
      at dispatch (/Users/kaixin1002/WebstormProjects/blog/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
      at /Users/kaixin1002/WebstormProjects/blog/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
      at dispatch (/Users/kaixin1002/WebstormProjects/blog/node_modules/koa-router/lib/router.js:351:31)
      at dispatch (/Users/kaixin1002/WebstormProjects/blog/node_modules/koa-compose/index.js:42:32)
      at /Users/kaixin1002/WebstormProjects/blog/node_modules/koa-compose/index.js:34:12
      at Application.handleRequest (/Users/kaixin1002/WebstormProjects/blog/node_modules/koa/lib/application.js:150:12)
      at Server.handleRequest (/Users/kaixin1002/WebstormProjects/blog/node_modules/koa/lib/application.js:132:19)
      at Server.emit (events.js:182:13)
      at parserOnIncoming (_http_server.js:658:12)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)

**Comment by liuxing** [comment]
模板引擎配置没？
